"""
Django settings for Tzmall project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#apps加入项目的根搜索路径
sys.path.insert(0,BASE_DIR)
sys.path.insert(0,os.path.join(
    BASE_DIR,'apps'
))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-alw77qms%5m8@4!l5g=sfs7%&ti54b8#)_tkwc(#wf(1&45gua'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['120.26.129.134','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cart',
    'comment',
    'goods',
    'order',
    'user',
    'menu',
    'address',
    'rest_framework',
    'corsheaders',
]

#允许所有域名跨域
CORS_ORIGIN_ALLOW_ALL = True
#允许携带cookie
CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'Tzmall.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Tzmall.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Tzmall',
        'HOST': '120.26.129.134',
        'PORT': 3306,
        'USER': 'root',
        'PASSWORD': 'Lzh040127',
        'POOL_OPTIONS': {
            'POOL_SIZE': 10,
            'MAX_OVERFLOW': 30,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR /'static']
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#静态文件地址

MEDIA_ROOT = BASE_DIR / 'downloads'
MEDIA_URL = '/downloads/'


PAGE_NUM = 20

#静态文件服务器配置
IMAGE_URL = 'http://120.26.129.134:8080/static/product_images/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':['utils.jwt_auth.JwtHeaderAuthentication']
}

# 配置redis缓存
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://120.26.129.134:8000/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": "Lzh040127!@#$%",  # 可含特殊字符，不需要 URL 编码
        }
    }
}

# 邮箱配置
# import ssl
# import certifi
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'       # SMTP服务器，比如QQ邮箱
EMAIL_PORT =587                # 端口，一般587或465
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = '3082566812@qq.com'   # 发送邮箱账号
EMAIL_HOST_PASSWORD = 'plkrqnacstvsdfig'     # 邮箱SMTP授权码（不是登录密码）
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# EMAIL_SSL_CONTEXT = ssl.create_default_context(cafile=certifi.where())


# 支付宝沙箱环境配置
APPID = '2021000149608922'
ALI_PUB_KEY_PATH = os.path.join(BASE_DIR, 'apps/pay/keys/alipaykey.txt')
PRIVATE_KEY_PATH = os.path.join(BASE_DIR, 'apps/pay/keys/private_key.txt')

# 异步接收url post
APP_NOTIFY_URL = 'http://120.26.129.134:8080/pay/alipay/return'
# 同步接收url get
RETURN_URL = 'http://120.26.129.134:8080/pay/alipay/return'
# 是否是开发环境
ALIPAY_DEBUG = True

